version: "3.8"

volumes:
  mariadb_data:

services:

  bot:
    container_name: bot
    image: jesuskris/kood-bot:tag
    labels:
      - autoheal=true
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:$PORT/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

    restart: always


  mariadb:
    container_name: database
    image: bitnami/mariadb:10.9
    labels:
      - autoheal=true
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
    user: root
    env_file:
      - .env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 10s

      retries: 5
    restart: always


  monitor:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    depends_on:
      mariadb:
        condition: service_healthy
      bot:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: always


  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup:3.5.5
    depends_on:
      mariadb:
        condition: service_healthy
    links:
     - mariadb
    volumes:
      - ./backups:/backup
    env_file:
      - .env
    restart: always

