version: "3.8"

services:

  bot:
    container_name: bot
    image: bot:latest
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: database
    image: bitnami/mariadb:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
      timeout: 5s
      retries: 10


